### PR TITLE
Fix some serialization bugs

### LINKED ISSUE #349: bug: `AttachmentBuilder#getBase64()` wrong mime type
**Describe the bug**
When invoking an instance of `AttachmentBuilder` (all constructors) and call `getBase64()`, it returns a wrong mime type.

**To Reproduce**
Create an instance of `AttachmentBuilder`, call `getBase64`

**Expected behavior**
The mime type should be: `data:image/{extension};base64,somelongencodeddata`, and currently, this is `data:image/.{extension};base64,somelongencodeddata`

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version 2.17.3
 - Nyxx version 4.0.0-dev.1

**Additional context**
None

### PR DESCRIPTION
**Pull request by Rapougnac**
# Description

Fix some serialization problems, `getBase64()` was working tho, but from discord's docs;

Image data is a [Data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) that supports JPG, GIF, and PNG formats. An example Data URI format is:
```
data:image/jpeg;base64,BASE64_ENCODED_JPEG_IMAGE_DATA
```

Fixes #349 and #350

## Connected issues & other potential problems
No

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] Ran `dart analyze` or `make analyze` and fixed all issues
- [ ] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my changes haven't lowered code coverage

### CODE REVIEW

File: lib/src/utils/builders/attachment_builder.dart [hunk 1]
```diff
@@ -62,7 +62,7 @@ class AttachmentBuilder {
   /// See: https://discord.com/developers/docs/reference#image-data
   String getBase64() {
     final encodedData = base64Encode(_bytes);
-    final extension = path_utils.extension(_name);
+    final extension = path_utils.extension(_name).substring(1);
```
Comment (abitofevrything) [inline lib/src/utils/builders/attachment_builder.dart:65]: This will throw if the file has no exception. It might be a good idea to include a "sensible default" like PNG in case the image file has no extension

Comment (abitofevrything) [reply lib/src/utils/builders/attachment_builder.dart:65]: Yeah - maybe extract `path_utils.extension(_name)` to a variable so we don't compute it twice but that's the idea. Even better - make `'png'` an optional named parameter named `defaultFormat`.

File: lib/src/utils/builders/attachment_builder.dart [hunk 2]
```diff
@@ -60,9 +60,11 @@ class AttachmentBuilder {
 
   /// Returns attachment encoded in Data URI scheme format
   /// See: https://discord.com/developers/docs/reference#image-data
-  String getBase64() {
+  String getBase64({String? defaultFormat = 'png'}) {
+    defaultFormat ??= 'png';
```
Comment (abitofevrything) [inline lib/src/utils/builders/attachment_builder.dart:64]: No need for this, the parameter can be non nullable with a default value

**Review by abitofevrything — CHANGES_REQUESTED** [review]

File: lib/src/utils/builders/attachment_builder.dart (hunk 2 above)
Comment (l7ssha) [reply lib/src/utils/builders/attachment_builder.dart:64]: better to remove `?` from type. Makes no sense if default parameter is present

Comment (Rapougnac) [reply lib/src/utils/builders/attachment_builder.dart:64]: Yeah, sorry, I'm not paying much attention today 😅

**Review by abitofevrything — APPROVED** [review]
