### PR TITLE
Replace (almost) all parsable enums to an enum-like class

### LINKED ISSUE #661: Hang Status is not handled
**Describe the bug**
Discord rolled out new feature called Hang Status for some users. Unfortunately, I wasn't able to find official docs for it, but there are a lot of articles in Google about it.

Apparently, this new status is not handled by [ActivityType](https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/models/presence.dart#L119) and whenever someone sets it, an exception is thrown. Now here comes another problem. After trying many different options to catch this exception, none of them actually worked (I tried adding `onError` callbacks, `handleError` calls, try/catch in different places, `runZoneGuarded`, etc., all this with and without `ignoreExceptions` plugin). Eventually, once this error occurs, bot stops listening to other commands and the only way to fix it is to restart the bot.

**To Reproduce**

- If you have Hang Status feature enabled for your account:
  - Join voice channel and set Hang status;
  - Start bot with `Nyxx.conntectGateway` call, use `GatewayIntents.all`;
  - Observe thrown exception - `FormatException: Unknown activity type`
- If you don't have new Hang status feature enabled for your account:
  - Remove `dnd` key from [UserStatus](https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/models/presence.dart#L28);
  - Set Do not disturb status on the account;
  - Start bot with `Nyxx.conntectGateway` call, use `GatewayIntents.all`;
  - Observe thrown exception - `FormatException: Unknown user status` (which leads to the same issue as described in the issue);

**Expected behavior**
Library correctly handles Hang status for the users.

**Desktop (please complete the following information):**
 - OS: Any;
 - Dart version: 3.3.4
 - Nyxx version: 6.2.1

### PR DESCRIPTION
**Pull request by Rapougnac**
# Description

## Connected issues & other potential problems
Closes #661 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (it's a partial breaking change?)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by l7ssha — APPROVED** [review]

File: lib/src/utils/enum_like.dart [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+  const EnumLike(this.value);
+
+  @override
+  String toString() => '$runtimeType($value)';
+
+  @override
+  int get hashCode => value.hashCode;
+
+  @override
+  bool operator ==(covariant EnumLike<T, U> other) => identical(this, other) || (other is U && other.value == value);
```
Comment (abitofevrything) [inline lib/src/utils/enum_like.dart:15]: The parameter should not be covariant, it should just be `Object`.

**Review by abitofevrything — CHANGES_REQUESTED** [review]
Could you also deprecate all the `parse` constructors? They will probably be removed eventually considering that they're now just duplicate functionality.

**Review by abitofevrything — APPROVED** [review]
